
package com.portal.web.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginAuthenticationSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoginAuthenticationSoap {


    /**
     * 通过Appkey获取需要创建业务系统帐号的用户列表
     * 
     * @param strAppKey
     * @param strTimeStamp
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "QueryUserNeedCreateByAppkey", action = "http://tempuri.org/QueryUserNeedCreateByAppkey")
    @WebResult(name = "QueryUserNeedCreateByAppkeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QueryUserNeedCreateByAppkey", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.QueryUserNeedCreateByAppkey")
    @ResponseWrapper(localName = "QueryUserNeedCreateByAppkeyResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.QueryUserNeedCreateByAppkeyResponse")
    public String queryUserNeedCreateByAppkey(
        @WebParam(name = "strAppKey", targetNamespace = "http://tempuri.org/")
        String strAppKey,
        @WebParam(name = "strTimeStamp", targetNamespace = "http://tempuri.org/")
        String strTimeStamp);

    /**
     * 通过UPN\Appkey 更新App帐号信息
     * 
     * @param strAppAccount
     * @param strUPN
     * @param strAppKey
     * @param strTimeStamp
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdataUserNeedCreateByAppkey", action = "http://tempuri.org/UpdataUserNeedCreateByAppkey")
    @WebResult(name = "UpdataUserNeedCreateByAppkeyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdataUserNeedCreateByAppkey", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UpdataUserNeedCreateByAppkey")
    @ResponseWrapper(localName = "UpdataUserNeedCreateByAppkeyResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UpdataUserNeedCreateByAppkeyResponse")
    public String updataUserNeedCreateByAppkey(
        @WebParam(name = "strUPN", targetNamespace = "http://tempuri.org/")
        String strUPN,
        @WebParam(name = "strAppKey", targetNamespace = "http://tempuri.org/")
        String strAppKey,
        @WebParam(name = "strAppAccount", targetNamespace = "http://tempuri.org/")
        String strAppAccount,
        @WebParam(name = "strTimeStamp", targetNamespace = "http://tempuri.org/")
        String strTimeStamp);

    /**
     * 通过帐号密码登录验证
     * 
     * @param strCPCAccount
     * @param strTimeStamp
     * @param strAppkey
     * @param strPassword
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UserAuthticationByCPCPhone", action = "http://tempuri.org/UserAuthticationByCPCPhone")
    @WebResult(name = "UserAuthticationByCPCPhoneResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserAuthticationByCPCPhone", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UserAuthticationByCPCPhone")
    @ResponseWrapper(localName = "UserAuthticationByCPCPhoneResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UserAuthticationByCPCPhoneResponse")
    public String userAuthticationByCPCPhone(
        @WebParam(name = "strCPCAccount", targetNamespace = "http://tempuri.org/")
        String strCPCAccount,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strTimeStamp", targetNamespace = "http://tempuri.org/")
        String strTimeStamp,
        @WebParam(name = "strAppkey", targetNamespace = "http://tempuri.org/")
        String strAppkey);

    /**
     * 通过帐号密码登录验证
     * 
     * @param strTimeStamp
     * @param strAppkey
     * @param strPassword
     * @param strAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UserAuthticationByAccountPwd", action = "http://tempuri.org/UserAuthticationByAccountPwd")
    @WebResult(name = "UserAuthticationByAccountPwdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserAuthticationByAccountPwd", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UserAuthticationByAccountPwd")
    @ResponseWrapper(localName = "UserAuthticationByAccountPwdResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UserAuthticationByAccountPwdResponse")
    public String userAuthticationByAccountPwd(
        @WebParam(name = "strAccount", targetNamespace = "http://tempuri.org/")
        String strAccount,
        @WebParam(name = "strPassword", targetNamespace = "http://tempuri.org/")
        String strPassword,
        @WebParam(name = "strTimeStamp", targetNamespace = "http://tempuri.org/")
        String strTimeStamp,
        @WebParam(name = "strAppkey", targetNamespace = "http://tempuri.org/")
        String strAppkey);

    /**
     * 通过域帐号登录验证
     * 
     * @param strTimeStamp
     * @param strAppkey
     * @param strAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UserAuthticationByAccount", action = "http://tempuri.org/UserAuthticationByAccount")
    @WebResult(name = "UserAuthticationByAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserAuthticationByAccount", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UserAuthticationByAccount")
    @ResponseWrapper(localName = "UserAuthticationByAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.UserAuthticationByAccountResponse")
    public String userAuthticationByAccount(
        @WebParam(name = "strAccount", targetNamespace = "http://tempuri.org/")
        String strAccount,
        @WebParam(name = "strTimeStamp", targetNamespace = "http://tempuri.org/")
        String strTimeStamp,
        @WebParam(name = "strAppkey", targetNamespace = "http://tempuri.org/")
        String strAppkey);

    /**
     * 通过TokenID登录验证
     * 
     * @param strTimeStamp
     * @param strAppkey
     * @param strTokenID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TokenAuthtication", action = "http://tempuri.org/TokenAuthtication")
    @WebResult(name = "TokenAuthticationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TokenAuthtication", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.TokenAuthtication")
    @ResponseWrapper(localName = "TokenAuthticationResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.TokenAuthticationResponse")
    public String tokenAuthtication(
        @WebParam(name = "strTokenID", targetNamespace = "http://tempuri.org/")
        String strTokenID,
        @WebParam(name = "strTimeStamp", targetNamespace = "http://tempuri.org/")
        String strTimeStamp,
        @WebParam(name = "strAppkey", targetNamespace = "http://tempuri.org/")
        String strAppkey);

    /**
     * 更新Token活跃时间
     * 
     * @param strTimeStamp
     * @param strAppkey
     * @param strTokenID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReletToken", action = "http://tempuri.org/ReletToken")
    @WebResult(name = "ReletTokenResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReletToken", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.ReletToken")
    @ResponseWrapper(localName = "ReletTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.ReletTokenResponse")
    public String reletToken(
        @WebParam(name = "strTokenID", targetNamespace = "http://tempuri.org/")
        String strTokenID,
        @WebParam(name = "strTimeStamp", targetNamespace = "http://tempuri.org/")
        String strTimeStamp,
        @WebParam(name = "strAppkey", targetNamespace = "http://tempuri.org/")
        String strAppkey);

    /**
     * MD5加密
     * 
     * @param strMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MD5Encrypt", action = "http://tempuri.org/MD5Encrypt")
    @WebResult(name = "MD5EncryptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MD5Encrypt", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.MD5Encrypt")
    @ResponseWrapper(localName = "MD5EncryptResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.MD5EncryptResponse")
    public String md5Encrypt(
        @WebParam(name = "strMessage", targetNamespace = "http://tempuri.org/")
        String strMessage);

    /**
     * MD5解密
     * 
     * @param strMessage
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MD5Decrypt", action = "http://tempuri.org/MD5Decrypt")
    @WebResult(name = "MD5DecryptResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MD5Decrypt", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.MD5Decrypt")
    @ResponseWrapper(localName = "MD5DecryptResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.MD5DecryptResponse")
    public String md5Decrypt(
        @WebParam(name = "strMessage", targetNamespace = "http://tempuri.org/")
        String strMessage);

    /**
     * 获取tadaddress
     * 
     * @param strSamAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ReadTagAddressBySamAccount", action = "http://tempuri.org/ReadTagAddressBySamAccount")
    @WebResult(name = "ReadTagAddressBySamAccountResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReadTagAddressBySamAccount", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.ReadTagAddressBySamAccount")
    @ResponseWrapper(localName = "ReadTagAddressBySamAccountResponse", targetNamespace = "http://tempuri.org/", className = "com.portal.web.client.ReadTagAddressBySamAccountResponse")
    public String readTagAddressBySamAccount(
        @WebParam(name = "strSamAccount", targetNamespace = "http://tempuri.org/")
        String strSamAccount);

}
